import Head from 'next/head'
import Card from '../components/Card';
import { server } from '../config';

export default function Home({data}) {
  return (
    <div>
      <Head>
        <title>Swadesh Task</title>
        <meta name="keywords" content="web development, coding" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-5">
        <h1 className="font-thicccboim text-white font-bold my-10 text-xl md:text-3xl lg:text-4xl">All properties</h1>
        {
          data.filter(each => each.funded < 100).map(each => (<div key={each.id} className="font-thicccboi">
            <Card each={each} />
          </div>))
        }
      
      <div>
        <h1 className="font-thicccboim  text-xl font-bold my-10 md:text-3xl lg:text-4xl">Past properties</h1>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 my-10 gap-3 md:gap-16  lg-max-h-2xl p-2 overflow-hidden">
        {
          data.filter(each => each.funded == 100).map(each => (<div key={each.id} className="font-thicccboi">
            <Card each={each} />
          </div>))
        }
        </div>
      </div>
      </div>
    </div>
  )
}

export async function getStaticProps(context){
  const res = await fetch(`${server}/api/basic`);
  const data = await res.json();

  if (!data){
    return {
      notFound: true
    }
  }

  return {
    props: { 
      data
    }
  }
}
